# Generated by Django 5.1.2 on 2024-11-24 14:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee_code', models.CharField(max_length=10, unique=True)),
                ('city_code', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('department_name', models.CharField(max_length=100)),
                ('department_number', models.CharField(max_length=10)),
                ('region_name', models.CharField(max_length=100)),
                ('region_geojson_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['label'],
            },
        ),
    ]
