# Generated by Django 5.1.2 on 2024-11-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_code',
            field=models.CharField(max_length=100),
        ),
    ]
