# Generated by Django 5.1.2 on 2024-11-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0002_alter_city_city_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='insee_code',
            field=models.CharField(max_length=10),
        ),
    ]
