# Generated by Django 5.1.2 on 2024-12-13 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClimbingGymLocations', '0004_remove_climbinggymlocations_lat_and_more'),
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_climbing_gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClimbingGymLocations.climbinggymlocations'),
        ),
    ]
