# Generated by Django 5.1.2 on 2024-11-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbingGymLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=100)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('big_city', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'verbose_name': "Salle d'escalade",
                'verbose_name_plural': "Salles d'escalade",
            },
        ),
    ]
