# Generated by Django 5.1.2 on 2024-10-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClimbingGymLocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climbinggymlocations',
            options={'verbose_name': "Salle d'escalade", 'verbose_name_plural': "Salles d'escalade"},
        ),
    ]
