# Generated by Django 5.1.2 on 2024-11-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClimbingGymLocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climbinggymlocations',
            options={'ordering': ['gym_name'], 'verbose_name': "Salle d'escalade", 'verbose_name_plural': "Salles d'escalade"},
        ),
        migrations.AlterField(
            model_name='climbinggymlocations',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='climbinggymlocations',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
