# Generated by Django 5.1.2 on 2024-10-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClimbingGymLocations', '0002_alter_climbinggymlocations_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbinggymlocations',
            name='big_city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='climbinggymlocations',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='climbinggymlocations',
            name='zip_code',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
