# Generated by Django 5.1.2 on 2024-11-24 14:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClimbingGymLocations', '0002_alter_climbinggymlocations_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbinggymlocations',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
