# Generated by Django 5.1.2 on 2024-11-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClimbingGymLocations', '0003_climbinggymlocations_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climbinggymlocations',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='climbinggymlocations',
            name='long',
        ),
    ]
