# Generated by Django 5.1.2 on 2025-01-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlannedClimbingSession', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedclimbingsession',
            name='end_time',
        ),
    ]
