# Generated by Django 5.1.2 on 2024-11-05 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClimbingGymLocations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.BooleanField(default=False, help_text='Is the difficulty color-coded ?')),
                ('label', models.CharField(help_text='Name or label of the difficulty', max_length=20)),
                ('hex_color', models.CharField(blank=True, help_text='haxe color code of the difficulty if color=True', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Difficulty',
                'verbose_name_plural': 'Difficulties',
            },
        ),
        migrations.CreateModel(
            name='ClimbingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('climb_type', models.CharField(choices=[('IN', 'Intérieur'), ('OUT', 'Extérieur')], default='IN', max_length=3)),
                ('height', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('climber', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClimbingGymLocations.climbinggymlocations')),
            ],
            options={
                'verbose_name': 'Session',
            },
        ),
        migrations.CreateModel(
            name='DifficultyCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, help_text='Number of times the difficulty was completed')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClimbingSession.difficulty')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_completions', to='ClimbingSession.climbingsession')),
            ],
            options={
                'verbose_name': 'Difficulty Completion',
                'verbose_name_plural': 'Difficulty Completions',
            },
        ),
        migrations.CreateModel(
            name='DifficultyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Ordre de la difficulté dans le set')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClimbingSession.difficulty')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DifficultySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulties', models.ManyToManyField(related_name='sets', through='ClimbingSession.DifficultyOrder', to='ClimbingSession.difficulty')),
            ],
            options={
                'verbose_name': 'Difficulty Set',
                'verbose_name_plural': 'Difficulty Sets',
            },
        ),
        migrations.AddField(
            model_name='difficultyorder',
            name='difficulty_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClimbingSession.difficultyset'),
        ),
        migrations.AddField(
            model_name='climbingsession',
            name='difficulty_set',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='ClimbingSession.difficultyset'),
        ),
    ]
