# Generated by Django 5.1.2 on 2024-10-30 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=100)),
                ('climb_type', models.CharField(choices=[('IN', 'Intérieur'), ('OUT', 'Extérieur')], default='IN', max_length=3)),
                ('height', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
