# Generated by Django 5.1.2 on 2024-11-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClimbingSession', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climbingsession',
            options={'ordering': ['-date'], 'verbose_name': 'Session'},
        ),
    ]
