# Generated by Django 5.1.2 on 2024-10-30 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClimbingGymLocations', '0002_alter_climbinggymlocations_options'),
        ('ClimbingSession', '0002_alter_climbingsession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbingsession',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClimbingGymLocations.climbinggymlocations'),
        ),
    ]
