# Generated by Django 5.1.2 on 2025-01-25 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClimbingSession', '0002_alter_climbingsession_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climbingsession',
            options={'ordering': ['-date_time_start'], 'verbose_name': 'Session'},
        ),
        migrations.RemoveField(
            model_name='climbingsession',
            name='date',
        ),
        migrations.AddField(
            model_name='climbingsession',
            name='date_time_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
